// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Belanosima, DM_Sans, Courier_Prime } from "next/font/google";
import "./globals.css";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { Toaster } from "@/components/ui/sonner";

const fontSans = Belanosima({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400"
});

const fontSerif = DM_Sans({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Courier_Prime({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased p-4 h-dvh overflow-x-hidden mt-26`}>
        {children}
        <ScrollProgress className="h-1.5" />
        <Toaster />
      </body>
    </html>
  );
}